version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
    environment:
      - DB_URL=postgresql+asyncpg://root:root@db:5432/fastapi_template
    depends_on:
      - db

  db:
    image: postgres:14.5-bullseye
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fastapi_template

    ports:
      - "5432:5432"

    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
